/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultaiRouteImport } from './routes/vaultai'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StackRouteImport } from './routes/stack'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MapRouteImport } from './routes/map'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfferSlugRouteImport } from './routes/offer.$slug'
import { Route as CompanyBrandRouteImport } from './routes/company.$brand'
import { Route as ApiV1SplatRouteImport } from './routes/api.v1.$'
import { Route as ApiPublicHooksSyncOffersRouteImport } from './routes/api/public/hooks/sync-offers'

const VaultaiRoute = VaultaiRouteImport.update({
  id: '/vaultai',
  path: '/vaultai',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferSlugRoute = OfferSlugRouteImport.update({
  id: '/offer/$slug',
  path: '/offer/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyBrandRoute = CompanyBrandRouteImport.update({
  id: '/company/$brand',
  path: '/company/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncOffersRoute =
  ApiPublicHooksSyncOffersRouteImport.update({
    id: '/api/public/hooks/sync-offers',
    path: '/api/public/hooks/sync-offers',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/achievements': typeof AchievementsRoute
  '/api-docs': typeof ApiDocsRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/dmca': typeof DmcaRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/stack': typeof StackRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/vaultai': typeof VaultaiRoute
  '/company/$brand': typeof CompanyBrandRoute
  '/offer/$slug': typeof OfferSlugRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/hooks/sync-offers': typeof ApiPublicHooksSyncOffersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/achievements': typeof AchievementsRoute
  '/api-docs': typeof ApiDocsRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/dmca': typeof DmcaRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/stack': typeof StackRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/vaultai': typeof VaultaiRoute
  '/company/$brand': typeof CompanyBrandRoute
  '/offer/$slug': typeof OfferSlugRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/hooks/sync-offers': typeof ApiPublicHooksSyncOffersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/achievements': typeof AchievementsRoute
  '/api-docs': typeof ApiDocsRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/calculator': typeof CalculatorRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/dmca': typeof DmcaRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/saved': typeof SavedRoute
  '/stack': typeof StackRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/vaultai': typeof VaultaiRoute
  '/company/$brand': typeof CompanyBrandRoute
  '/offer/$slug': typeof OfferSlugRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/public/hooks/sync-offers': typeof ApiPublicHooksSyncOffersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceptable-use'
    | '/achievements'
    | '/api-docs'
    | '/applications'
    | '/auth'
    | '/browse'
    | '/calculator'
    | '/calendar'
    | '/community'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/dmca'
    | '/map'
    | '/notifications'
    | '/privacy'
    | '/resources'
    | '/saved'
    | '/stack'
    | '/submit'
    | '/terms'
    | '/trending'
    | '/vaultai'
    | '/company/$brand'
    | '/offer/$slug'
    | '/api/v1/$'
    | '/api/public/hooks/sync-offers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceptable-use'
    | '/achievements'
    | '/api-docs'
    | '/applications'
    | '/auth'
    | '/browse'
    | '/calculator'
    | '/calendar'
    | '/community'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/dmca'
    | '/map'
    | '/notifications'
    | '/privacy'
    | '/resources'
    | '/saved'
    | '/stack'
    | '/submit'
    | '/terms'
    | '/trending'
    | '/vaultai'
    | '/company/$brand'
    | '/offer/$slug'
    | '/api/v1/$'
    | '/api/public/hooks/sync-offers'
  id:
    | '__root__'
    | '/'
    | '/acceptable-use'
    | '/achievements'
    | '/api-docs'
    | '/applications'
    | '/auth'
    | '/browse'
    | '/calculator'
    | '/calendar'
    | '/community'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/dmca'
    | '/map'
    | '/notifications'
    | '/privacy'
    | '/resources'
    | '/saved'
    | '/stack'
    | '/submit'
    | '/terms'
    | '/trending'
    | '/vaultai'
    | '/company/$brand'
    | '/offer/$slug'
    | '/api/v1/$'
    | '/api/public/hooks/sync-offers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  AchievementsRoute: typeof AchievementsRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CalculatorRoute: typeof CalculatorRoute
  CalendarRoute: typeof CalendarRoute
  CommunityRoute: typeof CommunityRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DmcaRoute: typeof DmcaRoute
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SavedRoute: typeof SavedRoute
  StackRoute: typeof StackRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  TrendingRoute: typeof TrendingRoute
  VaultaiRoute: typeof VaultaiRoute
  CompanyBrandRoute: typeof CompanyBrandRoute
  OfferSlugRoute: typeof OfferSlugRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiPublicHooksSyncOffersRoute: typeof ApiPublicHooksSyncOffersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaultai': {
      id: '/vaultai'
      path: '/vaultai'
      fullPath: '/vaultai'
      preLoaderRoute: typeof VaultaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$slug': {
      id: '/offer/$slug'
      path: '/offer/$slug'
      fullPath: '/offer/$slug'
      preLoaderRoute: typeof OfferSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$brand': {
      id: '/company/$brand'
      path: '/company/$brand'
      fullPath: '/company/$brand'
      preLoaderRoute: typeof CompanyBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-offers': {
      id: '/api/public/hooks/sync-offers'
      path: '/api/public/hooks/sync-offers'
      fullPath: '/api/public/hooks/sync-offers'
      preLoaderRoute: typeof ApiPublicHooksSyncOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  AchievementsRoute: AchievementsRoute,
  ApiDocsRoute: ApiDocsRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CalculatorRoute: CalculatorRoute,
  CalendarRoute: CalendarRoute,
  CommunityRoute: CommunityRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DmcaRoute: DmcaRoute,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SavedRoute: SavedRoute,
  StackRoute: StackRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  TrendingRoute: TrendingRoute,
  VaultaiRoute: VaultaiRoute,
  CompanyBrandRoute: CompanyBrandRoute,
  OfferSlugRoute: OfferSlugRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiPublicHooksSyncOffersRoute: ApiPublicHooksSyncOffersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
